export const ROUTES = {
  public: {
    landing: "/",
    login: "/login",
    register: "/cadastro",
    forgotPassword: "/recuperar-senha",
    explore: "/explorar",
    events: "/eventos",
    eventDetails: (eventId) => `/eventos/${eventId}`,
    ticketSelection: (eventId) => `/eventos/${eventId}/ingressos`,
    places: "/atrativos",
    placeDetails: (placeId) => `/atrativos/${placeId}`,
    tourism: "/turismo",
    tourismMap: "/turismo/mapa",
    attraction: (attractionId) => `/turismo/${attractionId}`,
    reservation: (attractionId) => `/turismo/${attractionId}/reserva`,
  },

  app: {
    home: "/home",
    cart: "/carrinho",
    checkout: "/checkout",
    order: (orderId) => `/pedidos/${orderId}`,
    tickets: "/ingressos",
    ticket: (ticketId) => `/ingressos/${ticketId}`,
    reservations: "/reservas",
    reservationConfirmation: (reservationId) => `/reservas/${reservationId}/confirmacao`,
    wallet: "/carteira",
    walletCashback: "/carteira/cashback",
    walletBenefits: "/carteira/beneficios",
    walletCoupons: "/carteira/cupons",
    walletPix: "/carteira/pix",
    walletCards: "/carteira/cartoes",
    walletStatement: "/carteira/extrato",
    favorites: "/favoritos",
    notifications: "/notificacoes",
    profile: "/perfil",
    settings: "/configuracoes",
  },

  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    events: "/admin/eventos",
    createEvent: "/admin/eventos/novo",
    editEvent: (eventId) => `/admin/eventos/${eventId}`,
    orders: "/admin/pedidos",
    reservations: "/admin/reservas",
    customers: "/admin/clientes",
    partners: "/admin/parceiros",
    financial: "/admin/financeiro",
    marketing: "/admin/marketing",
    reports: "/admin/relatorios",
    settings: "/admin/configuracoes",
  },
};
