export const ROUTES = {
  public: {
    landing: "/",
    login: "/login",
    register: "/cadastro",
    forgotPassword: "/recuperar-senha",
    explore: "/explorar",
    events: "/eventos",
    eventDetails: (eventId) => `/eventos/${eventId}`,
    places: "/atrativos",
    placeDetails: (placeId) => `/atrativos/${placeId}`,
  },

  app: {
    home: "/home",
    cart: "/carrinho",
    checkout: "/checkout",
    order: (orderId) => `/pedidos/${orderId}`,
    tickets: "/ingressos",
    ticket: (ticketId) => `/ingressos/${ticketId}`,
    reservations: "/reservas",
    wallet: "/carteira",
    favorites: "/favoritos",
    notifications: "/notificacoes",
    profile: "/perfil",
    settings: "/configuracoes",
  },

  admin: {
    root: "/admin",
    dashboard: "/admin/dashboard",
    events: "/admin/eventos",
    createEvent: "/admin/eventos/novo",
    editEvent: (eventId) => `/admin/eventos/${eventId}`,
    orders: "/admin/pedidos",
    reservations: "/admin/reservas",
    customers: "/admin/clientes",
    partners: "/admin/parceiros",
    financial: "/admin/financeiro",
    marketing: "/admin/marketing",
    reports: "/admin/relatorios",
    settings: "/admin/configuracoes",
  },
};
