export { default as WorkforceDashboardPage } from "./pages/WorkforceDashboardPage";
export { default as EmployeesPage } from "./pages/EmployeesPage";
export { default as EmployeeDetailsPage } from "./pages/EmployeeDetailsPage";
export { default as OrganizationChartPage } from "./pages/OrganizationChartPage";
export { default as PositionsPage } from "./pages/PositionsPage";
export { default as RecruitmentPage } from "./pages/RecruitmentPage";
export { default as CandidatesPage } from "./pages/CandidatesPage";
export { default as OnboardingPage } from "./pages/OnboardingPage";
export { default as SchedulesPage } from "./pages/SchedulesPage";
export { default as ShiftsPage } from "./pages/ShiftsPage";
export { default as AttendancePage } from "./pages/AttendancePage";
export { default as TimesheetsPage } from "./pages/TimesheetsPage";
export { default as LeavesPage } from "./pages/LeavesPage";
export { default as PayrollPage } from "./pages/PayrollPage";
export { default as BenefitsPage } from "./pages/BenefitsPage";
export { default as TrainingsPage } from "./pages/TrainingsPage";
export { default as CertificationsPage } from "./pages/CertificationsPage";
export { default as PerformancePage } from "./pages/PerformancePage";
export { default as GoalsPage } from "./pages/GoalsPage";
export { default as DevelopmentPage } from "./pages/DevelopmentPage";
export { default as ClimatePage } from "./pages/ClimatePage";
export { default as OccupationalHealthPage } from "./pages/OccupationalHealthPage";
export { default as ContractorsPage } from "./pages/ContractorsPage";
export { default as WorkforcePlanningPage } from "./pages/WorkforcePlanningPage";
export { default as WorkforceReportsPage } from "./pages/WorkforceReportsPage";
export { default as WorkforceSettingsPage } from "./pages/WorkforceSettingsPage";

export { useWorkforceDashboard } from "./hooks/useWorkforceDashboard";
export { workforceService } from "./services/workforceService";
export { workforcePlatformMock } from "./mocks/workforcePlatformMock";
