export { default as SafetyDashboardPage } from "./pages/SafetyDashboardPage";
export { default as LiveSafetyPage } from "./pages/LiveSafetyPage";
export { default as RiskMapPage } from "./pages/RiskMapPage";
export { default as RisksPage } from "./pages/RisksPage";
export { default as IncidentsPage } from "./pages/IncidentsPage";
export { default as IncidentDetailsPage } from "./pages/IncidentDetailsPage";
export { default as EmergencyPlansPage } from "./pages/EmergencyPlansPage";
export { default as AccessControlPage } from "./pages/AccessControlPage";
export { default as CredentialsPage } from "./pages/CredentialsPage";
export { default as CamerasPage } from "./pages/CamerasPage";
export { default as SensorsPage } from "./pages/SensorsPage";
export { default as CapacityPage } from "./pages/CapacityPage";
export { default as EvacuationsPage } from "./pages/EvacuationsPage";
export { default as MusterPointsPage } from "./pages/MusterPointsPage";
export { default as MedicalPostsPage } from "./pages/MedicalPostsPage";
export { default as AmbulancesPage } from "./pages/AmbulancesPage";
export { default as MedicalOccurrencesPage } from "./pages/MedicalOccurrencesPage";
export { default as MissingPersonsPage } from "./pages/MissingPersonsPage";
export { default as CrisisRoomPage } from "./pages/CrisisRoomPage";
export { default as AuthoritiesPage } from "./pages/AuthoritiesPage";
export { default as SafetyReportsPage } from "./pages/SafetyReportsPage";
export { default as SafetySettingsPage } from "./pages/SafetySettingsPage";

export { useSafetyDashboard } from "./hooks/useSafetyDashboard";
export { safetyService } from "./services/safetyService";
export { safetyPlatformMock } from "./mocks/safetyPlatformMock";
