export const AGENT_PERMISSIONS = {
  VIEW: 'agents.view',
  CREATE: 'agents.create',
  UPDATE: 'agents.update',
  DELETE: 'agents.delete',

  APPROVE: 'agents.approve',
  SUSPEND: 'agents.suspend',
  REACTIVATE: 'agents.reactivate',

  VIEW_DOCUMENTS: 'agents.documents.view',
  MANAGE_DOCUMENTS: 'agents.documents.manage',

  VIEW_SCHEDULE: 'agents.schedule.view',
  MANAGE_SCHEDULE: 'agents.schedule.manage',

  VIEW_COMMISSIONS: 'agents.commissions.view',
  MANAGE_COMMISSIONS: 'agents.commissions.manage',

  VIEW_PERFORMANCE: 'agents.performance.view',
  MANAGE_PERFORMANCE: 'agents.performance.manage',

  VIEW_LOCATION: 'agents.location.view',
  MANAGE_LOCATION: 'agents.location.manage',

  EXPORT: 'agents.export',
};

export const AGENT_PERMISSION_GROUPS = {
  BASIC: [
    AGENT_PERMISSIONS.VIEW,
  ],

  OPERATIONAL: [
    AGENT_PERMISSIONS.VIEW,
    AGENT_PERMISSIONS.CREATE,
    AGENT_PERMISSIONS.UPDATE,
    AGENT_PERMISSIONS.VIEW_SCHEDULE,
    AGENT_PERMISSIONS.MANAGE_SCHEDULE,
  ],

  MANAGEMENT: [
    AGENT_PERMISSIONS.VIEW,
    AGENT_PERMISSIONS.CREATE,
    AGENT_PERMISSIONS.UPDATE,
    AGENT_PERMISSIONS.DELETE,
    AGENT_PERMISSIONS.APPROVE,
    AGENT_PERMISSIONS.SUSPEND,
    AGENT_PERMISSIONS.REACTIVATE,
    AGENT_PERMISSIONS.VIEW_DOCUMENTS,
    AGENT_PERMISSIONS.MANAGE_DOCUMENTS,
    AGENT_PERMISSIONS.VIEW_SCHEDULE,
    AGENT_PERMISSIONS.MANAGE_SCHEDULE,
    AGENT_PERMISSIONS.VIEW_COMMISSIONS,
    AGENT_PERMISSIONS.MANAGE_COMMISSIONS,
    AGENT_PERMISSIONS.VIEW_PERFORMANCE,
    AGENT_PERMISSIONS.MANAGE_PERFORMANCE,
    AGENT_PERMISSIONS.VIEW_LOCATION,
    AGENT_PERMISSIONS.EXPORT,
  ],
};
